language: bash
services: docker

env:
  - VERSION=7.0 VARIANT=cli

install:
  - git clone https://github.com/hellofresh/docker-php-ci.git ~/docker-php-ci

before_script:
  - env | sort
  - cd ~/docker-php-ci/$VERSION/$VARIANT
  - image="docker-php-ci:${VERSION}-${VARIANT}"

script:
  - travis_retry docker build -t "$image" .

after_script:
  - docker images
  - docker login --username="$QUAY_USER" --password="$QUAY_PASS" quay.io
  - docker push quay.io/hellofresh/$image

# vim:set et ts=2 sw=2:
